# Generated by Django 2.2.2 on 2024-11-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('RICE', 'RICE'), ('PANCAKE', 'PANCAKE'), ('BEVERAGES', 'BEVERAGES')], default='RICE', max_length=250)),
                ('base_size_unit', models.CharField(choices=[('KG', 'KG'), ('PISCES', 'PISCES'), ('LITTERS', 'LITTERS')], default='KG', max_length=250)),
                ('serving_size_unit', models.CharField(choices=[('PISCES', 'PISCES'), ('LADDLE', 'LADDLE'), ('GLASS', 'GLASS')], default='LADDLE', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], default='LUNCH', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('in_campus', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], default='LUNCH', max_length=250)),
                ('meal_preference', models.CharField(choices=[('FULL', 'FULL'), ('HALF', 'HALF'), ('CUSTOM', 'CUSTOM'), ('SKIPPED', 'SKIPPED')], default='FULL', max_length=250)),
                ('meal_status', models.CharField(choices=[('ATE', 'ATE'), ('SKIPPED', 'SKIPPED'), ('NULL', 'NULL')], default='NULL', max_length=250)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to='meals.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to='meals.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCustomMealItem',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('meal_qty', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meal_items', to='meals.Item')),
                ('user_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_meal_items', to='meals.UserMeal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('full_meal_qty', models.PositiveIntegerField(default=0)),
                ('half_meal_qty', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_meal_items', to='meals.Item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='meals.Meal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
