# Generated by Django 2.2.2 on 2024-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommealitem',
            old_name='custom_meal_qty',
            new_name='meal_qty',
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='meal_status',
            field=models.CharField(choices=[('ATE', 'ATE'), ('SKIPPED', 'SKIPPED'), ('NULL', 'NULL')], default='NULL', max_length=250),
        ),
    ]
