# Generated by Django 2.2.2 on 2024-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20241115_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeal',
            name='meal_preference',
            field=models.CharField(choices=[('FULL', 'FULL'), ('HALF', 'HALF'), ('CUSTOM', 'CUSTOM'), ('SKIPPED', 'SKIPPED')], default='FULL', max_length=250),
        ),
    ]
