# Generated by Django 2.2.2 on 2024-11-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20241115_1608'),
        ('meals', '0004_auto_20241114_1707'),
    ]

    operations = [
    ]
